### ISSUE TITLE
Don't request pages from reddit 

### ISSUE THREAD

**Issue by inigoserna** [simon1573/teddit-redirect#4] opened 2020-12-12 11:28 UTC
I'm not an expert on javascript neither on firefox addons, so take these comments with proper caution and excuse me for any inaccuracies.

I think that that this addon redirects to teddit *after loading* original reddit page. Is it correct?

Looking at https://addons.mozilla.org/en-US/firefox/addon/old-reddit-redirect/ addon it should be possible to make the URL change before performing the request [1].

In fact I've modified this addon with code taken from old-reddit-redirect and it works perfectly.
Something like:

```
const oldReddit = "https://teddit.net";
const excludedPaths = [
  "/gallery",
  "/poll",
  "/rpan",
  "/settings",
  "/topics"];

chrome.webRequest.onBeforeRequest.addListener(
  function(details) {
      const url = new URL(details.url);

      if (url.hostname === "teddit.net") return;

      for (const path of excludedPaths) {
          if (url.pathname.indexOf(path) === 0) return;
      }

      return {redirectUrl: oldReddit + url.pathname + url.search + url.hash};
  },
    {
        urls: [
            "*://reddit.com/*",
            "*://www.reddit.com/*",
            "*://np.reddit.com/*",
            "*://new.reddit.com/*",
            "*://amp.reddit.com/*",
        ],
        types: [
            "main_frame",
            "sub_frame",
            "stylesheet",
            "script",
            "image",
            "object",
            "xmlhttprequest",
            "other"
        ]
    },
    ["blocking"]
);
```

What do you think?

[1] https://github.com/tom-james-watson/old-reddit-redirect/blob/master/background.js

**Comment by simon1573** [comment] 2021-01-07 15:42
Hey inigoserna! Thanks for going the extra mile with this issue. I've updated the way the plugin is invoked and since the last few versions the plugin should load almost instantly, hence I'm closing this issue for now.

**Closed by simon1573** 2021-01-07 15:42 UTC

**Comment by inigoserna** [comment] 2021-01-07 20:09
The issue is not the speed, but the unnecessary load of reddit page first. More time, and more data and more exposure to reddit javascript code.

**Comment by tdeeb** [comment] 2021-01-18 01:42
@simon1573 I would also like to see this addressed. I see reddit requests coming in when it should be redirecting me straight to teddit.

**Comment by flux77** [comment] 2023-05-07 21:31
@simon1573 Why was this bug report closed? The problem is still there. Please reopen this issue.
